#!/usr/bin/env bash

CYCLELEN=${1}
AVG=${2:a}
POLICY=${3}

NATTACKS=(1 2 3 4)
CHAINLENGTHS=(2 3 4)
TESTSET=(klimentova20 klimentova50 klimentova100)

declare -A POLICIES
POLICIES=( [1]="Full Recourse" [2]="FSE" )

declare -A NODES
NODES=( [klimentova20]=" 20" [klimentova50]=" 50" [klimentova100]="100" )



# output header
echo "% generated by paper_generate_table.sh ${CYCLELEN} ${AVG} ${POLICY}"
echo "\begin{sidewaystable}"
echo "  \begin{scriptsize}"
echo "    \caption{Comparison of the different methods for maximum cycle length ${CYCLELEN} and different chain lengths, for the ${POLICIES[${POLICY}]} policy.}"
echo "    \label{tab:cyc${CYCLELEN}-policy${POLICY}}"

if [[ ${POLICY} -eq 1 ]]
then
	echo "    \begin{tabular*}{\textwidth}{@{}l@{\;\;\extracolsep{\fill}}rrrrrrrrrrrrrrrrr@{}}\toprule"
	echo "       & \multicolumn{5}{c}{Branch-and-Bound} & \multicolumn{6}{c}{cut-CC} & \multicolumn{6}{c}{cut-PICEF}\\\\"
	echo "      \cmidrule{2-6} \cmidrule{7-12} \cmidrule{13-18}"
	echo "      & & \multicolumn{2}{c}{time} & & & & \multicolumn{3}{c}{time} & & & & \multicolumn{3}{c}{time} & & \\\\"
	echo "      \cmidrule{3-4} \cmidrule{8-10} \cmidrule{14-16}"
	echo "      \#vertices & \#opt & total & stage 2 & \#att. & \#B\&B-nodes & \#opt & total & stage 2 & stage 3 & \#att. & \#sub & \#opt & total & stage 2 & stage 3 & \#att. & \#sub \\\\"

	# output results
	for CHAIN in ${CHAINLENGTHS[@]}
	do
		echo "      \midrule"
		echo "      \multicolumn{18}{@{}l}{chain length: "$CHAIN"}\\\\"

		for N in ${NATTACKS[@]}
		do
		echo "      \multicolumn{18}{@{}l}{\$B = "$N"\$}\\\\"
		for T in ${TESTSET[@]}
		do
			LOGSTART=../check/results/check.mcs.default.q.$T.nattacks$N.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.mcs-login001.

			A=$(python3 paper_extract_info.py $LOGSTART"method3-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy${POLICY}.out" 0 $AVG)
			B=$(python3 paper_extract_info.py $LOGSTART"method1-complexFALSE-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy${POLICY}.out" 1 $AVG)
			C=$(python3 paper_extract_info.py $LOGSTART"method2-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy${POLICY}.out" 1 $AVG)
			echo "      "${NODES[$T]}" & "$A" & "$B" & "$C"\\\\"
		done
		done
	done
else
	echo "    \begin{tabular*}{\textwidth}{@{}l@{\;\;\extracolsep{\fill}}rrrrrrrrrrrr@{}}\toprule"
	echo "       & \multicolumn{6}{c}{cut-CC} & \multicolumn{6}{c}{cut-PICEF}\\\\"
	echo "      \cmidrule{2-7} \cmidrule{8-13}"
	echo "      & & \multicolumn{3}{c}{time} & & & & \multicolumn{3}{c}{time} & & \\\\"
	echo "      \cmidrule{3-5} \cmidrule{9-11}"
	echo "      \#vertices & \#opt & total & stage 2 & stage 3 & \#att. & \#sub & \#opt & total & stage 2 & stage 3 & \#att. & \#sub \\\\"

	# output results
	for CHAIN in ${CHAINLENGTHS[@]}
	do
		echo "      \midrule"
		echo "      \multicolumn{13}{@{}l}{chain length: "$CHAIN"}\\\\"

		for N in ${NATTACKS[@]}
		do
		echo "      \multicolumn{13}{@{}l}{\$B = "$N"\$}\\\\"
		for T in ${TESTSET[@]}
		do
			LOGSTART=../check/results/check.mcs.default.q.$T.nattacks$N.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.mcs-login001.

			B=$(python3 paper_extract_info.py $LOGSTART"method1-complexFALSE-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy${POLICY}.out" 1 $AVG)
			C=$(python3 paper_extract_info.py $LOGSTART"method2-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy${POLICY}.out" 1 $AVG)
			echo "      "${NODES[$T]}" & "$B" & "$C"\\\\"
		done
		done
	done
fi

#output footer
echo "      \bottomrule"
echo "    \end{tabular*}"
echo "  \end{scriptsize}"
echo "\end{sidewaystable}"
