#!/usr/bin/env bash

CYCLELEN=${1}
AVG=${2:a}
METHOD=${3:c}
POLICY=${4}

MAXNATTACKS=4
CHAINLENGTHS=(2 3 4)
TESTSET=(klimentova20 klimentova50 klimentova100)

declare -A NODES
NODES=( [klimentova20]=" 20" [klimentova50]=" 50" [klimentova100]="100" )

declare -A METHODNAME
METHODNAME=( [c]="cut-CC" [p]="cut-PICEF" )

declare -A METHODNUMBER
METHODNUMBER=( [c]="1" [p]="2" )

declare -A POLICIES
POLICIES=( [1]="Full Recourse" [2]="FSE" )

# output header
echo "% generated by paper_generate_aggr_lifting_table.sh ${CYCLELEN} ${AVG} ${METHOD} ${POLICY}"
echo "\begin{table}"
echo "  \begin{scriptsize}"
echo "    \caption{Comparison of the ${METHODNAME[$METHOD]} method with and without lifting for maximum cycle length ${CYCLELEN} and different chain lengths, for the ${POLICIES[$POLICY]} policy.}"
echo "    \label{tab:aggrlifting_cyc${CYCLELEN}-method${METHODNUMBER[$METHOD]}-policy${POLICY}}"
echo "    \begin{tabular*}{\textwidth}{@{}l@{\;\;\extracolsep{\fill}}rrrrrrrr@{}}\toprule"
echo "       & \multicolumn{4}{c}{with lifting} & \multicolumn{4}{c}{without lifting}\\\\"
echo "      \cmidrule{2-5} \cmidrule{6-9}"
echo "      \#vertices & \#opt & time & \#att. & \#sub & \#opt & time & \#att. & \#sub \\\\"

# output results
for CHAIN in ${CHAINLENGTHS[@]}
do
    echo "      \midrule"
    echo "      \multicolumn{9}{@{}l}{chain length: "$CHAIN"}\\\\"

    for T in ${TESTSET[@]}
    do
		LOGSTART=../check/results/check.mcs.default.q.$T.nattacks
		if [[ ${METHODNUMBER[$METHOD]} -eq "1" ]]
		then
			LOGMIDA=.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.mcs-login001.method1-complexFALSE-cyc${CYCLELEN}-chain${CHAIN}-liftTRUE-policy$POLICY.out
			LOGMIDB=.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.mcs-login001.method1-complexFALSE-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy$POLICY.out
		else
			LOGMIDA=.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.mcs-login001.method2-cyc${CYCLELEN}-chain${CHAIN}-liftTRUE-policy$POLICY.out
			LOGMIDB=.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.mcs-login001.method2-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy$POLICY.out
		fi

		A=$(python3 paper_extract_aggr_info.py $LOGSTART $LOGMIDA $MAXNATTACKS $AVG)
		B=$(python3 paper_extract_aggr_info.py $LOGSTART $LOGMIDB $MAXNATTACKS $AVG)
		echo "      "${NODES[$T]}" & "$A" & "$B"\\\\"
    done
done

#output footer
echo "      \bottomrule"
echo "    \end{tabular*}"
echo "  \end{scriptsize}"
echo "\end{table}"
