#!/usr/bin/env bash

CYCLELEN=${1}
AVG=${2:a}
METHOD=${3:c}

NATTACKS=(1 2 3 4)
CHAINLENGTHS=(2 3 4)
TESTSET=(klimentova20 klimentova50 klimentova100)

declare -A NODES
NODES=( [klimentova20]=" 20" [klimentova50]=" 50" [klimentova100]="100" )

declare -A METHODNAME
METHODNAME=( [c]="Benders" [p]="Benders PICEF" )

declare -A METHODNUMBER
METHODNUMBER=( [c]="1" [p]="2" )

# output header
echo "% generated by paper_generate_lifting_table.sh ${CYCLELEN} ${AVG} ${METHOD}"
echo "\begin{sidewaystable}"
echo "  \begin{scriptsize}"
echo "    \caption{Comparison of the ${METHODNAME[$METHOD]} method with and without lifting for maximum cycle length ${CYCLELEN} and different chain lengths.}"
echo "    \label{tab:lifting_cyc${CYCLELEN}-${METHOD}}"
echo "    \begin{tabular*}{\textwidth}{@{}l@{\;\;\extracolsep{\fill}}rrrrrrrrrrrr@{}}\toprule"
echo "       & \multicolumn{6}{c}{with lifting} & \multicolumn{6}{c}{without lifting}\\\\"
echo "      \cmidrule{2-7} \cmidrule{8-13}"
echo "      & & \multicolumn{3}{c}{time} & & & & \multicolumn{3}{c}{time} & & \\\\"
echo "      \cmidrule{3-5} \cmidrule{9-11}"
echo "      \#vertices & \#opt & total & stage 2 & stage 3 & \#att. & \#sub & \#opt & total & stage 2 & stage 3 & \#att. & \#sub \\\\"

# output results
for CHAIN in ${CHAINLENGTHS[@]}
do
    echo "      \midrule"
    echo "      \multicolumn{13}{@{}l}{chain length: "$CHAIN"}\\\\"

    for N in ${NATTACKS[@]}
    do
	echo "      \multicolumn{13}{@{}l}{"\$B = "$N"\$}\\\\"
	for T in ${TESTSET[@]}
	do
	    LOGSTART=results/check.moskito.$T.nattacks$N.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.moskito.

	    A=$(python paper_extract_info.py $LOGSTART"method${METHODNUMBER[${METHOD}]}-cyc${CYCLELEN}-chain${CHAIN}.out" 1 $AVG)
	    B=$(python paper_extract_info.py $LOGSTART"nolift_method${METHODNUMBER[${METHOD}]}-cyc${CYCLELEN}-chain${CHAIN}.out" 1 $AVG)
	    echo "      "${NODES[$T]}" & "$A" & "$B"\\\\"
	done
    done
done

#output footer
echo "      \bottomrule"
echo "    \end{tabular*}"
echo "  \end{scriptsize}"
echo "\end{sidewaystable}"
