#!/usr/bin/env bash

CYCLELEN=${1}
AVG=${2:a}
METHOD=${3:c}
POLICY=${4}

NATTACKS=(1 2 3 4)
CHAINLENGTHS=(2 3 4)
TESTSET=(klimentova20 klimentova50 klimentova100)

declare -A NODES
NODES=( [klimentova20]=" 20" [klimentova50]=" 50" [klimentova100]="100" )

declare -A METHODNAME
METHODNAME=( [c]="cut-CC" [p]="cut-PICEF" )

declare -A METHODNUMBER
METHODNUMBER=( [c]="1" [p]="2" )

declare -A POLICIES
POLICIES=( [1]="Full Recourse" [2]="FSE")

# output header
echo "% generated by paper_generate_lifting_table.sh ${CYCLELEN} ${AVG} ${METHOD} ${POLICY}"
echo "\begin{sidewaystable}"
echo "  \begin{scriptsize}"
echo "    \caption{Comparison of the ${METHODNAME[$METHOD]} method with and without lifting for maximum cycle length ${CYCLELEN} and different chain lengths, for the ${POLICIES[$POLICY]} policy.}"
echo "    \label{tab:lifting-cyc${CYCLELEN}-method${METHODNUMBER[$METHOD]}-policy${POLICY}}"
echo "    \begin{tabular*}{\textwidth}{@{}l@{\;\;\extracolsep{\fill}}rrrrrrrrrrrr@{}}\toprule"
echo "       & \multicolumn{6}{c}{with lifting} & \multicolumn{6}{c}{without lifting}\\\\"
echo "      \cmidrule{2-7} \cmidrule{8-13}"
echo "      & & \multicolumn{3}{c}{time} & & & & \multicolumn{3}{c}{time} & & \\\\"
echo "      \cmidrule{3-5} \cmidrule{9-11}"
echo "      \#vertices & \#opt & total & stage 2 & stage 3 & \#att. & \#sub & \#opt & total & stage 2 & stage 3 & \#att. & \#sub \\\\"

# output results
for CHAIN in ${CHAINLENGTHS[@]}
do
    echo "      \midrule"
    echo "      \multicolumn{13}{@{}l}{chain length: "$CHAIN"}\\\\"

    for N in ${NATTACKS[@]}
    do
		echo "      \multicolumn{13}{@{}l}{"\$B = $N"\$}\\\\"
		for T in ${TESTSET[@]}
		do
			LOGSTART=../check/results/check.mcs.default.q.$T.nattacks$N.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.mcs-login001.
			if [[ ${METHODNUMBER[$METHOD]} -eq "1" ]]
			then

				A=$(python3 paper_extract_info.py $LOGSTART"method1-complexFALSE-cyc${CYCLELEN}-chain${CHAIN}-liftTRUE-policy${POLICY}.out" 1 $AVG)
				B=$(python3 paper_extract_info.py $LOGSTART"method1-complexFALSE-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy${POLICY}.out" 1 $AVG)
			else
				A=$(python3 paper_extract_info.py $LOGSTART"method2-cyc${CYCLELEN}-chain${CHAIN}-liftTRUE-policy${POLICY}.out" 1 $AVG)
				B=$(python3 paper_extract_info.py $LOGSTART"method2-cyc${CYCLELEN}-chain${CHAIN}-liftFALSE-policy${POLICY}.out" 1 $AVG)
			fi
			echo "      "${NODES[$T]}" & "$A" & "$B"\\\\"
		done
    done
done

#output footer
echo "      \bottomrule"
echo "    \end{tabular*}"
echo "  \end{scriptsize}"
echo "\end{sidewaystable}"
