#!/usr/bin/env bash

CYCLELEN=${1}
AVG=${2:a}

NATTACKS=(1 2 3 4)
CHAINLENGTHS=(2 3 4)
TESTSET=(klimentova20 klimentova50 klimentova100)

declare -A NODES
NODES=( [klimentova20]=" 20" [klimentova50]=" 50" [klimentova100]="100" )


# output header
echo "% generated by paper_generate_table.sh ${CYCLELEN} ${AVG}"
echo "\begin{sidewaystable}"
echo "  \begin{scriptsize}"
echo "    \caption{Comparison of the different methods for maximum cycle length ${CYCLELEN} and different chain lengths.}"
echo "    \label{tab:cyc${CYCLELEN}}"
echo "    \begin{tabular*}{\textwidth}{@{}l@{\;\;\extracolsep{\fill}}rrrrrrrrrrrrrrrrr@{}}\toprule"
echo "       & \multicolumn{5}{c}{Branch-and-Bound} & \multicolumn{6}{c}{Benders} & \multicolumn{6}{c}{Benders PICEF}\\\\"
echo "      \cmidrule{2-6} \cmidrule{7-12} \cmidrule{13-18}"
echo "      & & \multicolumn{2}{c}{time} & & & & \multicolumn{3}{c}{time} & & & & \multicolumn{3}{c}{time} & & \\\\"
echo "      \cmidrule{3-4} \cmidrule{8-10} \cmidrule{14-16}"
echo "      \#vertices & \#opt & total & stage 2 & \#att. & \#B\&B-nodes & \#opt & total & stage 2 & stage 3 & \#att. & \#sub & \#opt & total & stage 2 & stage 3 & \#att. & \#sub \\\\"

# output results
for CHAIN in ${CHAINLENGTHS[@]}
do
    echo "      \midrule"
    echo "      \multicolumn{18}{@{}l}{chain length: "$CHAIN"}\\\\"

    for N in ${NATTACKS[@]}
    do
	echo "      \multicolumn{18}{@{}l}{\$B = "$N"\$}\\\\"
	for T in ${TESTSET[@]}
	do
	    LOGSTART=results/check.moskito.$T.nattacks$N.fullrecoursekidney.linux.x86_64.gnu.opt.spx2.moskito.

	    A=$(python paper_extract_info.py $LOGSTART"method3-cyc${CYCLELEN}-chain${CHAIN}.out" 0 $AVG)
	    B=$(python paper_extract_info.py $LOGSTART"method1-cyc${CYCLELEN}-chain${CHAIN}.out" 1 $AVG)
	    C=$(python paper_extract_info.py $LOGSTART"method2-cyc${CYCLELEN}-chain${CHAIN}.out" 1 $AVG)
	    echo "      "${NODES[$T]}" & "$A" & "$B" & "$C"\\\\"
	done
    done
done

#output footer
echo "      \bottomrule"
echo "    \end{tabular*}"
echo "  \end{scriptsize}"
echo "\end{sidewaystable}"
